### ISSUE TITLE
deleting before reconciling and posting is BAD!

### ISSUE THREAD

**Issue by CanDKD** [uic-utah/reconcile-and-post#1]
Let's make sure that we can't run **delete.bat** before running **reconcile.bat**

**Comment by steveoh** [comment]
And the way to know that reconcile has been run would be by?

**Comment by CanDKD** [comment]
When reconcile has been run, the -RnP- versions are created.  Those version don't get deleted until the delete function is run.  If delete doesn't see any RnP versions then reconcile has not been run.  If delete does not see RnP version then delete should fail.

I have an idea.  How about a .bat called rnp_delete.bat which calls both reconcile and delete.  That  way delete can never be run with out first reconciling and posting.

**Comment by steveoh** [comment]
we can delete the delete.bat if you want but i think it is still useful

**Comment by CanDKD** [comment]
No, let's not delete delete.bat.  I think the 'exit early if rnp versions do not exist' should cover it.
